### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by justinwasilenko** [jacksondunstan/NativeCollections#1]
First, love your blog so many great articles well written and informative.

Second, I just tried importing NativeCollections into a new empty project and I get this error message:

Assets\JacksonDunstanNativeCollections\NativeLinkedList.cs(1128,20): error CS7036: There is no argument given that corresponds to the required formal parameter 'allocator' of 'DisposeSentinel.Create(out AtomicSafetyHandle, out DisposeSentinel, int, Allocator)'

Is says in the readme that Jobs or Burst aren't necessary. Is there something else that I need?

Using Unity 2018.3.0f2.

**Comment by jacksondunstan** [comment]
Hi @justinwasilenko, thanks for reporting this issue! You shouldn't need Jobs or Burst or any packages. The error was simply the lack of a preprocessor check for Unity 2018.3 to comply with the new, backwards-incompatible API of `DisposeSentinel.Create`. I've fixed the problem in 9fd6db308c957c4a5c83555a970164b3e9611162, so please pull and try again. If the problem persists, please re-open this issue.
