### ISSUE TITLE
NativeChunkedList<T> memory overwrite when it grows Capacity 

### ISSUE THREAD

**Issue by rswa** [jacksondunstan/NativeCollections#16]
NativeChunkedList<T>.cs 1267 line  
sizeof(NativeChunkedListChunk) => sizeof(NativeChunkedListChunk*)
miss a * for the pointers

`// Copy the old chunk pointers to the new chunk pointers
						UnsafeUtility.MemCpy(
							`chunks,`
							m_State->m_Chunks,
	sizeof(NativeChunkedListChunk) * numOldChunks);`

**Comment by jacksondunstan** [comment]
Thanks for letting me know! I pushed your suggested fix.
