### ISSUE TITLE
NativeHashSet.ParallelWriter error with Unity 2019.2

### ISSUE THREAD

**Issue by sebas77** [jacksondunstan/NativeCollections#4]
I have two problems, however the first one may be a current limitation of Unity (that's why I am not opening another issue)

1) I can't use [DeallocateOnJobCompletion] on NativeHashSet so I am forced to use a persistent one

2) Using the parallel writer I get this error:

InvalidOperationException: ListTriggerEventEntitiesJob.UserJobData.TriggerdContactsWriter uses the [NativeContainer] but has no AtomicSafetyHandle embedded, this is an internal error in the container type.

**Comment by jacksondunstan** [comment]
Hi @sebas77,

1. `[DeallocateOnJobCompletion]` requires the container to have `[NativeContainerSupportsDeallocateOnJobCompletion]` which requires the container to have `int* m_Buffer` and `Allocator m_AllocatorLabel` which it uses to deallocate. `NativeHashSet` doesn't have that, so it can't have `[NativeContainerSupportsDeallocateOnJobCompletion]` or support `[DeallocateOnJobCompletion]`. Other, simpler collections like `NativeIntPtr` in this repo do support `[DeallocateOnJobCompletion]` though.
2. I don't get this error when running the performance tests. Can you share an example job that triggers this error?

Thanks,
-Jackson

**Comment by Karmoq** [comment]
Hey, I just ran into the same error for the second problem.

Here is my Test that Im running which has the same error:
```
[Test]
		public void TestParallelWriting()
		{
			NativeArray<int> readArray = new NativeArray<int>(8128, Allocator.Temp);
			for (int i = 0; i < readArray.Length; i++)
			{
				readArray[i] = i;
			}

			NativeHashSet<int> writeHashSet = new NativeHashSet<int>(8128, Allocator.Temp);

			var writeJob = new WriteParallelJob()
			{
				readArray = readArray,
				writeHashSet = writeHashSet.AsParallelWriter()
			};

			var handle = writeJob.Schedule(readArray.Length, 16);
			handle.Complete();

			NativeArray<int> checkArray = writeHashSet.ToNativeArray();
			for (int i = 0; i < checkArray.Length; i++)
			{
				if (checkArray[i] != readArray[i])
				{
					Assert.Fail();
				}
			}

			readArray.Dispose();
			checkArray.Dispose();
			writeHashSet.Dispose();
		}
```

EDIT: Im running this in 2019.3.6f1 and with Collections package 0.7.0

**Comment by jacksondunstan** [comment]
@Karmoq I'd like to be able to run your test, but it's incomplete such as by omitting `WriteParallelJob`. Can you provide a more complete example, such as a fork of the repo?

**Comment by Karmoq** [comment]
Hey, sorry, of course I shouldve put the job in there -.-

Heres a fork of the repo with a test that fails due to an error of the nativehashset:
https://github.com/Karmoq/NativeCollections
I also added a Package Versions file. Im using the currently newest versions of all the dots packages, maybe they changed something within the last few days

**Comment by jacksondunstan** [comment]
I found and fixed the issue in this commit:
5e9142f62f39096988ba9fa40c69cfba45c4ac25

Thank you both for reporting the issue!
