### ISSUE TITLE
NativeArray2D: Multi-dimensional vs Jagged Arrays Performance

### ISSUE THREAD

**Issue by hiradyazdan** [jacksondunstan/NativeCollections#8]
I am wondering whether your approach on implementing a 2d nativeArray could have performance implications, specially when used in the job system. Unity also advised that [iterating over multidimensional arrays are less efficient than jagged and one dimensional arrays](https://docs.unity3d.com/2019.3/Documentation/Manual/BestPracticeUnderstandingPerformanceInUnity8.html). 

Wouldn't it be more efficient to flatten the multidimensional/jagged arrays into one dimensional native arrays (with modified indices) and then use that for jobs?

**Comment by jacksondunstan** [comment]
@hiradyazdan The article you linked to is specifically talking about C#'s managed multi-dimensional arrays. `NativeArray2D` is structured differently as accesses are simply indexing into a single-dimensional array. See here for the code:

https://github.com/jacksondunstan/NativeCollections/blob/master/JacksonDunstanNativeCollections/NativeArray2D.cs#L365

**Comment by hiradyazdan** [comment]
@jacksondunstan I think the indexer code you gave is essentially calculating the address of the array element in memory layout which is how multi dimensional arrays (i.e. rectangular sequential arrays) work anyway, not a single dimensional array index. So, I'm not sure if that counts. I might be missing a point though, so please elaborate.

Edit: I came to conclusion that the C# JIT optimizes the multidimensional arrays less efficient than they should be (i.e. in C/C++), so jagged arrays in that article results in having better performance. So as you said it's the C# managed arrays issue and accessing unmanaged arrays with a buffer index would behave more efficient.
